export const quotes: string[] = [
  "The code you write makes you a programmer. The code you delete makes you a good one.",
  "Programming isn't about what you know; it's about what you can figure out.",
  "Talk is cheap. Show me the code.",
  "Before software can be reusable it first has to be usable.",
  "Everybody should learn to program a computer because it teaches you how to think.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "The best error message is the one that never shows up.",
  "One of the best programming skills you can have is knowing when to walk away for a while.",
  "It's not a bug – it's an undocumented feature.",
  "First, solve the problem. Then, write the code.",
  "Make it work, make it right, make it fast.",
  "Clean code always looks like it was written by someone who cares.",
  "Debugging is twice as hard as writing the code in the first place.",
  "Code is like humor. When you have to explain it, it's bad.",
  "Good things take time",
  "Almost there… great things loading",
  "Loading your experience, please wait",
  "Patience is the key to something amazing",
  "Preparing something awesome for you",
  "Hang tight! We’re getting things ready",
  "Every moment counts—loading in progress",
  "Your content is on its way",
  "Getting things ready for you",
  "Just a moment — we're on it",
  "Loading your experience",
  "Almost there",
  "Good things take a moment",
  "Thanks for your patience",
  "Worth the wait",
  "Something good is coming",
  "Preparing something awesome",
  "Your journey continues",
  "Hang tight",
  "We’re setting things up",
  "Making things smooth for you",
  "Loading creativity, please wait.",
  "Good things take time, even code.",
  "Every great app starts with a small idea.",
  "Turning coffee into code.",
  "Loading progress, stay curious.",
  "Building something meaningful.",
  "Small steps lead to big results.",
  "Coding the future, one line at a time.",
  "Patience is part of the process.",
  "Almost there, thank you for waiting."
];
